mcom: Enable CONFIG_DM_DEVICE_REMOVE
The option is required to avoid an error during rescan USB bus:

  Error: Cannot find high speed parent of usb-1 device ...

Issue: #MCOM02SW-808
Change-Id: I1c1e39970565653b80041e0cc696bfde1f2c2dd2