mcom02: Fix bootargs when building without their support
If some commands, e.g. DHCP/PXE, are disabled then the compilation
fails due to bootargs attempting to use them:

  include/config_distro_bootcmd.h:319:2: error: expected ‘}’ before ‘BOOT_TARGET_DEVICES_references_PXE_without_CONFIG_CMD_DHCP_or_PXE’

Ensure that if the command aren't enabled, we don't try and use them.

Issue: #MCOM02SW-2284
Change-Id: I4e4f6ef8847e2f80e3968f2188e1e2c36f3b0afc