mcom02: dts: Delete VPU memory reserving
There is no driver for VPU in U-Boot. As U-Boot DTS are not used for
Linux anymore, there is no need to keep nodes that are not used in
U-Boot.

This will fix memory reservation errors in U-Boot:

  ERROR: reserving fdt memory region failed

Issue: #MCOM02SW-2130
Change-Id: I03482f2a9bae151ae5caaf14cab7d8c47a4f38c2